### ISSUE TITLE
The "HTML Env Replacement" feature is not work inside the <?php ?> tag

### ISSUE THREAD

**Issue by ian-ng** [donnikitos/vite-plugin-php#15]
The "HTML Env Replacement" feature is not work inside the <?php ?> tag.

Issue:
- Input 
```
// path: env/.env
VITE_ENV=development

// path: index.php
<?php $env = "%VITE_ENV%";?>
```
- Output (Issue)
```
// path: index.php
<?php $env = "%VITE_ENV%";?>
```

- Expected output
```
// path: index.php
<?php $env = "development";?>
```

**Comment by donnikitos** [comment]
Uh, that's an interesting one since the PHP snippets are
inserted post compilation 🤔
But I agree - it is definitely a nice feature to have!
Will definitely look into it.
