### ISSUE TITLE
Should this be hot reloading automatically?

### ISSUE THREAD

**Issue by christoferd** [donnikitos/vite-plugin-php#2]
Hi, Should this be hot reloading automatically?

When I edit the index.php file the page does not hot reload automatically.
Vite output in CLI does notice the change and outputs this:

`3:35:24 pm [vite] page reload src/index.php`

**Comment by donnikitos** [comment]
Hi, the plugin is not hot reloading. Instead it does a full reload of the page.
Have you added a proper `entry` to your config?
Something like: 
```
usePHP({
	entry: ['src/index.php'],
});
```

By default the plugin loads the `index.php` from the root, just like Vite would with the `index.html`.

**Comment by donnikitos** [comment]
I assume the reloading issue is resolved
