### ISSUE TITLE
php/html changes are not being updated in the tmp files...

### ISSUE THREAD

**Issue by verhulstd** [donnikitos/vite-plugin-php#20]
first of all thx for the great work!
css and js are being updated while making changes. 
When changing the html/php the browser also reloads but the '.php-tmp' files are not overwritten with the new changes.
When restarting the dev server the tmp files are overwritten with the correct contents...
(using windows)

**Comment by donnikitos** [comment]
I am glad you find the plugin useful!

Strange and interesting bug; well during debugging I was only able to find, that if you have a wildcard entry selector and you add new .php files they won't be processed and you need to restart the server.
Is that your issue?

If not a few steps to reproduce would be really helpful :)

**Comment by kartofelek007** [comment]
I also got this error.
My simple config:
https://domanart.pl/inne_rzeczy/php-vite-test.zip

After running, changes in scss work as expected, but changes in php are not registered (nothing happens in the terminal)

**Comment by donnikitos** [comment]
@kartofelek007 thanks for submitting more details.
Are you using Node or Bun? And which versions?
I will try to replicate it on my Windows machine.

**Comment by kartofelek007** [comment]
node -v
v20.17.0

js work, scss work, but nothing happend when i change php.
Also when I kill process with Ctrl + C something like this appear:

![image](https://github.com/user-attachments/assets/35189f70-d4b6-4404-b74f-d35a5073dce8)

**Comment by donnikitos** [comment]
Bug found - fix is coming tonight.
Turned out to be a minor, but pretty obvious thing: Windows has a slightly different file path structure...
