### ISSUE TITLE
prevent injection of @vite/client script tag

### ISSUE THREAD

**Issue by krei-se** [donnikitos/vite-plugin-php#27]
i try to export to json from a php file and get an @vite/client script tag on top of the returned php page.

I know i can somehow inject a middleware to prevent this, but i would love to know if there is an easier way.

On another note: It's unclear a bit to me how you include partials in your starter repo. There are php files directly in /partials like nav.php included, but folder/**/*.php would only include php files in subdirectories for me.

Currently i help myself with a mishmash of vite-plugin-static-copy and render on my webserver, but i would love php integration on my dev side.

I will look into these issues on my own but maybe those issues are bothering someone else too :)

**Comment by donnikitos** [comment]
Hi @krei-se,

first of all, thanks for the coffee and the issue submission :)

For the compilation partials are processed via Vite in the [config file](https://github.com/nititech/php-vite-starter/blob/master/vite.config.ts#L21):
![image](https://github.com/user-attachments/assets/7e7b8762-e41c-4128-8646-bcdb70c75dc6)
So all PHP-files in the `partials/` subdirectory will be transpiled.
In PHP you need to include them as usual with an [`include()` statement](https://github.com/nititech/php-vite-starter/blob/master/pages/index.php#L8):
![image](https://github.com/user-attachments/assets/bc1190b4-1041-4f77-a354-67a8425d1a34)

For this to work you the [`index.php`](https://github.com/nititech/php-vite-starter/blob/master/index.php#L7) is adding the root of the project to the `include_path`:
![image](https://github.com/user-attachments/assets/23a7e509-f41f-4b47-95c0-6becb3555b29)

---

Regarding the JSON output - I understand the error, that you are getting, but I do not fully understand, how to reproduce it. Do you have some example code?
This error usually happens, if the router can not find the correct file. Have you tried adding the file, or file extension to the [`rewriteUrl()` routing configuration](https://github.com/nititech/php-vite-starter/blob/master/vite.config.ts#L22)?

**Comment by krei-se** [comment]
I'm making progress after breaking it even more.

```
                        usePHP({
                                entry: ['index.php', 'php/*.php', 'php/**/*.php']
                        }),
```
this works somewhat, but the issue is, that i cannot include with just relative paths from any php file that is not in the root of the project. f.e. if you have a file under php, __FILE__ / __DIR__ will get the router.php and you always need to full include path for anything under /php/include/functions or similar. a file under /php can not include "subdir/another.php".

But for now that's just the way it is and it works somewhat with full paths! :)

On the other issue: I use php for backend processing of stuff i don't want in any .ts files and want to have a php script send json:

```
<?php

$data = "Test.JSON";
header('Content-Type: application/json; charset=utf-8');
echo json_encode($data);

?>
```
saved under /php/json.php and defined as an entry point gets as output:

```
<script type="module" src="/@vite/client"></script>
 "Test.JSON" 
```

**Comment by donnikitos** [comment]
Pretty strange behavior to be honest 🤔
Is your main entry file the [index.php from the starter repo](https://github.com/nititech/php-vite-starter/blob/master/index.php)?
Does your config allow you to set `ini_set('include_path')`?

---

BTW, you can simplify your entry config to:
```
                        usePHP({
                                entry: ['index.php', 'php/**/*.php']
                        }),
```
This should cover all *.php files inside the `php/` folder.

---

Alright, I see what the problem with JSON is: Vite tries to transpile it, as if it is HTML. That's not a big issue, a solution could be to read the response headers of the PHP server and determine what content type it is. If it's not `text/html` -> don't put it in the transpilation pipeline.

I can tackle that issue somewhere to the end of the week, stay tuned :)

**Comment by donnikitos** [comment]
@krei-se I understood your problem and have created a separate ticket for that, since that is a whole other thing to tackle 🤔

In the mean time you could import your files as if everything is project root based:
```php
// /php/include/functions/databasefunctions.php

include('php/include/db.php');
```

**Comment by krei-se** [comment]
Thanks so much! I'm totally fine with this solution as i'm on a new project and this does not bug me that much. I can relate to the pain trying to make it work anyhow so im still impressed i can have a dev-setup like this!

Parsing xml from fetched .php output is fine and works around the script-issue for now but it will break any legacy software someone is trying to modernize.

This is more about having it adopted more easily to other devs. I tried nodejs for backend or vite/typescript for simple webpages and i cannot understand why people would replace a mature ecosystem like PHP.

Expect more debugging from me though as i will use this for a while :D

All the best!
