### ISSUE TITLE
Support wildcards in entries

### ISSUE THREAD

**Issue by skabeche** [donnikitos/vite-plugin-php#4]
Hi, I'm trying wildcards and they don't work.
```
  plugins: [
    usePHP({
      entry: [
        "index.php",
        "partials/*.php",
      ]
    })
  ],
```
![image](https://github.com/donnikitos/vite-plugin-php/assets/17012986/efe2597d-b781-4e1a-ba47-be844464fbab)

I have to define each file to make it work:
```
  plugins: [
    usePHP({
      entry: [
        "index.php",
        "partials/nav-top.php",
        "partials/message.php",
        "partials/footer.php",
      ]
    })
  ],
```
Is it possible to use wildcards in entries?

Thanks.

**Comment by donnikitos** [comment]
Yes as for now this feature is not supported.
But it is definitely coming in the near future!
