### ISSUE TITLE
Using XAMPP on windows

### ISSUE THREAD

**Issue by J0T0S0** [donnikitos/vite-plugin-php#9]
I'm currently using xampp on windows and when i go to the register.php page it shows these errors:

Warning: Unknown: Failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Failed opening required '/C:/Users/galli/OneDrive/Desktop/Locker/Projects/Websites/JTS Projects/jts-website/node_modules/vite-plugin-php/dist/router.php' (include_path='C:\xampp\php\PEAR') in Unknown on line 0

Config:

    plugins: [
        usePHP({
            binary: "/xampp/php",
            entry: ["register.php", "confirm.php"],
        }),

**Comment by donnikitos** [comment]
Does your PHP development server start?
You should see something like this:
![image](https://github.com/donnikitos/vite-plugin-php/assets/5833538/99a45cd2-2bb0-4b16-a45d-493d20a57b07)

**Comment by J0T0S0** [comment]
Nevermind, just created my own php runner with a few lines of code
